// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwxWtkmvGxny2hNjf-wAOu4Vf4rjrsM3E',
    appId: '1:1054513382343:web:ce5f5126c3be473e0c4fe2',
    messagingSenderId: '1054513382343',
    projectId: 'mapforevents-3fd0c',
    authDomain: 'mapforevents-3fd0c.firebaseapp.com',
    storageBucket: 'mapforevents-3fd0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACsUkVyXJ-m1TrtPWy3GY0BBwnxwohZmE',
    appId: '1:1054513382343:android:0b731a1f834146f70c4fe2',
    messagingSenderId: '1054513382343',
    projectId: 'mapforevents-3fd0c',
    storageBucket: 'mapforevents-3fd0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACOcKYen3t9r189cUQ6o5mwrVKFwlpnv8',
    appId: '1:1054513382343:ios:ed2716676ec751aa0c4fe2',
    messagingSenderId: '1054513382343',
    projectId: 'mapforevents-3fd0c',
    storageBucket: 'mapforevents-3fd0c.appspot.com',
    iosBundleId: 'com.example.mapForEvents',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACOcKYen3t9r189cUQ6o5mwrVKFwlpnv8',
    appId: '1:1054513382343:ios:49705f64ab03b5fb0c4fe2',
    messagingSenderId: '1054513382343',
    projectId: 'mapforevents-3fd0c',
    storageBucket: 'mapforevents-3fd0c.appspot.com',
    iosBundleId: 'com.example.mapForEvents.RunnerTests',
  );
}
